version: "3.9"
services:
  backend:
    image: crud
    container_name: crud
    restart: always
    ports:
      - "80:8080"
    environment:
      SPRING_PROFILES_ACTIVE: main
      SERVER_PORT: 8080
      POSTGRES_DB: jdbc:postgresql://database:5432/postgres
      POSTGRES_USER: crud
      POSTGRES_PASSWORD: crud

  activemq:
    image: rmohr/activemq:5.14.0
    container_name: activemq
    ports:
      - "61616:61616"
    environment:
      ACTIVEMQ_CONFIG_NAME: "amqp"
      ACTIVEMQ_CONFIG_DEFAULTACCOUNT: "true"
      ACTIVEMQ_ADMIN_LOGIN: "admin"
      ACTIVEMQ_ADMIN_PASSWORD: "admin"
      ACTIVEMQ_CONFIG_QUEUES: "pdfQueue"

  database:
    image: postgres:15
    restart: always
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: crud
      POSTGRES_PASSWORD: crud
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: