spring:
    application:
        name: crud

    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://3.77.203.112:5432/postgres
        username: crud
        password: crud

    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true

server:
    error:
        include-stacktrace: always

app:
    jwt:
        secret: mukhammed.codes